server {
    # Указываем 80 порт для соединения
    listen 80;
    # Какому доменному имени принадлежит наш конфиг
    server_name localhost;

    # Задаём корневую директорию
    root /data/anbprog.local;

    # Стартовый файл
    index index.php index.html;

    # При обращении к статическим файлам логи не нужны, равно как и обращение к fpm
    # http://anbprog.local/static/some.png
    location ~* .(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log off;
        expires max;
    }

    # Помним про единую точку доступа
    # Все запросы заворачиваются в корневую директорию root на index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Правило обращения к php-fpm
    location ~* .php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass php-fpm:9000;
        #fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
